### ISSUE TITLE
Code includes ability to alter or adjust input data

### ISSUE THREAD

**Issue by danielkoexe** [justinklee345/cs225ProjectHelloHello#15]
Change main function so that it takes in multiple arguments, the file path for the dataset and the number of node ids in the dataset.

**Comment by danielkoexe** [comment]
Similar to 

https://courses.engr.illinois.edu/cs225/fa2022/mps/mosaics/ 

https://github.com/cs225-illinois/release-f22/blob/main/mp_mosaics/entry/mosaics.cpp

update main to take in dataset path and node id size.
int main(int argc, const char** argv) { ....

**Comment by justinklee345** [comment]
resolved this issue using argv
